// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGhnobrbfKOM_pJjLjuwsdq-i3hZmUKqY',
    appId: '1:44011533978:web:3a101bd1f782520dfb1123',
    messagingSenderId: '44011533978',
    projectId: 'mentimeterclone-d624e',
    authDomain: 'mentimeterclone-d624e.firebaseapp.com',
    storageBucket: 'mentimeterclone-d624e.firebasestorage.app',
    measurementId: 'G-GN8H97NXMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOJGbdZcA9_a8mR3yNAV-ZgYvX7r6hTEs',
    appId: '1:44011533978:android:ebf11b8629b7a2c6fb1123',
    messagingSenderId: '44011533978',
    projectId: 'mentimeterclone-d624e',
    storageBucket: 'mentimeterclone-d624e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6pEzIU_Vb-j5BLM8X_vO0OCKGG5UGWjs',
    appId: '1:44011533978:ios:07dab624edceed34fb1123',
    messagingSenderId: '44011533978',
    projectId: 'mentimeterclone-d624e',
    storageBucket: 'mentimeterclone-d624e.firebasestorage.app',
    iosBundleId: 'com.example.adminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6pEzIU_Vb-j5BLM8X_vO0OCKGG5UGWjs',
    appId: '1:44011533978:ios:07dab624edceed34fb1123',
    messagingSenderId: '44011533978',
    projectId: 'mentimeterclone-d624e',
    storageBucket: 'mentimeterclone-d624e.firebasestorage.app',
    iosBundleId: 'com.example.adminApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGhnobrbfKOM_pJjLjuwsdq-i3hZmUKqY',
    appId: '1:44011533978:web:80a244410ee92bddfb1123',
    messagingSenderId: '44011533978',
    projectId: 'mentimeterclone-d624e',
    authDomain: 'mentimeterclone-d624e.firebaseapp.com',
    storageBucket: 'mentimeterclone-d624e.firebasestorage.app',
    measurementId: 'G-1ZFEL1J6LE',
  );
}
